# Generated by Django 4.2.5 on 2024-01-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
