# Generated by Django 4.2.5 on 2024-01-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_rename_product_city_rename_category_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='category',
            new_name='country',
        ),
    ]
