# Generated by Django 4.2.5 on 2024-01-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_rename_category_city_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='country',
            new_name='department',
        ),
    ]
